server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone=http://localhost:8761/eureka:
spring:
  application:
    name: flight-service
  datasource:
    url: jdbc:h2:mem:flightdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
